create: help text and option processing for the `drive` suite

diff --git a/bin/drive- b/bin/drive-
--- a/bin/drive-
+++ b/bin/drive-
@@ -3,6 +3,50 @@ source '/home/nestor/bin/std.lib'
 
 # ---
 
+{ # -- Help Text -- #
+
+	cat <<-EOF | store-as usage
+		Usage: $( script-name )
+
+		Unmounts the Google Drive "shell-transfers" directory from "~/drive".
+
+		Mandatory arguments to long options are mandatory for short options too.
+		  --help                    Show this help text.
+
+		Exit status:
+		  0  if OK,
+		  1  if invalid option.
+	EOF
+
+}
+
+# ---
+
+{ # -- Parameter Processing: Options -- #
+
+	CHAR_OPTS=''
+	LONG_OPTS='help'
+
+	set-params
+	while true; do
+		option="$1" && shift
+		case "$option" in
+			(--help) exit-out "$usage" ;;
+			(--) break ;;  # No more options.
+		esac
+	done
+
+}
+
+{ # -- Parameter Processing: Positionals -- #
+
+	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+
+}
+
+# ---
+# ---
+
 
 drive_mount="${HOME}/drive"
 'drive?' && sync "$drive_mount" && umount "$drive_mount" && rmdir "$drive_mount"
diff --git a/bin/drive? b/bin/drive?
--- a/bin/drive?
+++ b/bin/drive?
@@ -3,6 +3,50 @@ source '/home/nestor/bin/std.lib'
 
 # ---
 
+{ # -- Help Text -- #
+
+	cat <<-EOF | store-as usage
+		Usage: $( script-name )
+
+		Reports whether "~/drive" is an active Google Drive mount.
+
+		Mandatory arguments to long options are mandatory for short options too.
+		  --help                    Show this help text.
+
+		Exit status:
+		  0  if mount is active,
+		  1  if no active mount.
+	EOF
+
+}
+
+# ---
+
+{ # -- Parameter Processing: Options -- #
+
+	CHAR_OPTS=''
+	LONG_OPTS='help'
+
+	set-params
+	while true; do
+		option="$1" && shift
+		case "$option" in
+			(--help) exit-out "$usage" ;;
+			(--) break ;;  # No more options.
+		esac
+	done
+
+}
+
+{ # -- Parameter Processing: Positionals -- #
+
+	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+
+}
+
+# ---
+# ---
+
 
 drive_mount="${HOME}/drive"
 findmnt --types=fuse.google-drive-ocamlfuse "$drive_mount" &> /dev/null
