mod: rename "std.lib"-provided error helpers and normalize usage
The old "error-out"/"exit-out" names signaled *behaviour*, not *intent*.

diff --git a/filesets/home/bin/available-port b/filesets/home/bin/available-port
--- a/filesets/home/bin/available-port
+++ b/filesets/home/bin/available-port
@@ -38,7 +38,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -51,7 +51,7 @@ source '/home/nestor/bin/std.lib'
 	[ -n "$port_or_range" ] || port_or_range='3001-3999'
 
 
-	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+	[ "$#" == 0 ] || user-error 1 'invalid option(s)'
 
 }
 
@@ -65,21 +65,24 @@ ss --all --ipv4 --numeric --no-header 2> /dev/null | awk '{ print $5 }' | cut -d
 #
 if 'numeric?' "$port_or_range"; then
 	if 'has-line?' "$port_or_range" <<< "$ports_in_use"
-		then exit-out 1
-		else exit-out 0
+		then exit 1
+		else exit 0
 	fi
 
 # We've been given a RANGE.
 #
 elif 'has-line?' --regex '\d+-\d+' <<< "$port_or_range"; then
 	shuf --input-range="$port_or_range" | while read -r port; do
-		'has-line?' "$port" <<< "$ports_in_use" || exit-out 0 "$port"
+		if ! 'has-line?' "$port" <<< "$ports_in_use"; then
+			echo "$port"
+			exit 0
+		fi
 	done
 
-	exit-out 2
+	non-user-error 2
 
 # Unexpected param formatting.
 #
 else
-	error-out 1 'unexpected param formatting'
+	user-error 1 'unexpected param formatting'
 fi
diff --git a/filesets/home/bin/calc? b/filesets/home/bin/calc?
--- a/filesets/home/bin/calc?
+++ b/filesets/home/bin/calc?
@@ -39,7 +39,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -50,11 +50,11 @@ source '/home/nestor/bin/std.lib'
 # ---
 
 
-output="$( calc -- "$@" 2> /dev/null )" || error-out 2 'invalid expression'
+output="$( calc -- "$@" 2> /dev/null )" || user-error 2 'invalid expression'
 
 case "$output" in
-	0) exit-out 1 ;;
-	1) exit-out 0 ;;
+	0) exit 1 ;;
+	1) exit 0 ;;
 
-	*) error-out 2 'non-boolean result' ;;
+	*) user-error 2 'non-boolean result' ;;
 esac
diff --git a/filesets/home/bin/mariadb? b/filesets/home/bin/mariadb?
--- a/filesets/home/bin/mariadb?
+++ b/filesets/home/bin/mariadb?
@@ -33,7 +33,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -42,7 +42,7 @@ source '/home/nestor/bin/std.lib'
 
 { # -- Parameter Processing: Positionals -- #
 
-	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+	[ "$#" == 0 ] || user-error 1 'invalid option(s)'
 
 }
 
@@ -65,7 +65,7 @@ else
 
 	# We need to *ask* the 'mariadb' instance.
 	#
-	[ "$( gcp state mariadb )" == 'RUNNING' ] || exit-out 1
+	[ "$( gcp state mariadb )" == 'RUNNING' ] || exit 1
 	gcp run mariadb "$local_service_check" | lines &> /dev/null
 
 fi
diff --git a/filesets/home/bin/spring- b/filesets/home/bin/spring-
--- a/filesets/home/bin/spring-
+++ b/filesets/home/bin/spring-
@@ -33,7 +33,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -42,7 +42,7 @@ source '/home/nestor/bin/std.lib'
 
 { # -- Parameter Processing: Positionals -- #
 
-	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+	[ "$#" == 0 ] || user-error 1 'invalid option(s)'
 
 }
 
@@ -50,5 +50,5 @@ source '/home/nestor/bin/std.lib'
 # ---
 
 
-command -v spring &> /dev/null || exit-out 0
+command -v spring &> /dev/null || exit 0
 spring stop &> /dev/null
diff --git a/filesets/home/bin/spring? b/filesets/home/bin/spring?
--- a/filesets/home/bin/spring?
+++ b/filesets/home/bin/spring?
@@ -34,7 +34,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -43,7 +43,7 @@ source '/home/nestor/bin/std.lib'
 
 { # -- Parameter Processing: Positionals -- #
 
-	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+	[ "$#" == 0 ] || user-error 1 'invalid option(s)'
 
 }
 
@@ -51,5 +51,5 @@ source '/home/nestor/bin/std.lib'
 # ---
 
 
-command -v spring &> /dev/null || exit-out 1
+command -v spring &> /dev/null || exit 1
 spring status | head -n1 | sed -e 's|:$|.|' | tee /dev/stderr | 'has?' 'is running'
diff --git a/filesets/home/bin/swap b/filesets/home/bin/swap
--- a/filesets/home/bin/swap
+++ b/filesets/home/bin/swap
@@ -36,7 +36,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -46,13 +46,13 @@ source '/home/nestor/bin/std.lib'
 { # -- Parameter Processing: Positionals -- #
 
 	file_1="$1" && shift
-	[ -n "$file_1" ] || error-out 1 '2 files required'
+	[ -n "$file_1" ] || user-error 1 '2 files required'
 
 	file_2="$1" && shift
-	[ -n "$file_2" ] || error-out 1 '2 files required'
+	[ -n "$file_2" ] || user-error 1 '2 files required'
 
 
-	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+	[ "$#" == 0 ] || user-error 1 'invalid option(s)'
 
 }
 
@@ -62,8 +62,8 @@ source '/home/nestor/bin/std.lib'
 
 # Make sure the files exist.
 
-[ -e "$file_1" ] || error-out 2 "file not found: '${file_1}'"
-[ -e "$file_2" ] || error-out 2 "file not found: '${file_2}'"
+[ -e "$file_1" ] || user-error 2 "file not found: '${file_1}'"
+[ -e "$file_2" ] || user-error 2 "file not found: '${file_2}'"
 
 
 # Make sure file locations are writable.
@@ -74,13 +74,13 @@ dirname "$file_2" | store-as dir_2
 TMPDIR="$dir_1" tempname | store-as temp_1
 TMPDIR="$dir_2" tempname | store-as temp_2
 
-[ -w "$dir_1" ] || error-out 3 'write access denied'
-[ -w "$dir_2" ] || error-out 3 'write access denied'
+[ -w "$dir_1" ] || non-user-error 3 'write access denied'
+[ -w "$dir_2" ] || non-user-error 3 'write access denied'
 
 
 # Swap the files.
 
-mv "$file_1" "$temp_1" || {                                                   error-out 4 'swap not allowed' ;}
-mv "$file_2" "$temp_2" || { mv "$temp_1" "$file_1" ;                          error-out 4 'swap not allowed' ;}
-mv "$temp_1" "$file_2" || { mv "$temp_1" "$file_1" ; mv "$temp_2" "$file_2" ; error-out 4 'swap not allowed' ;}
-mv "$temp_2" "$file_1" || { mv "$file_2" "$file_1" ; mv "$temp_2" "$file_2" ; error-out 4 'swap not allowed' ;}
+mv "$file_1" "$temp_1" || {                                                   non-user-error 4 'swap not allowed' ;}
+mv "$file_2" "$temp_2" || { mv "$temp_1" "$file_1" ;                          non-user-error 4 'swap not allowed' ;}
+mv "$temp_1" "$file_2" || { mv "$temp_1" "$file_1" ; mv "$temp_2" "$file_2" ; non-user-error 4 'swap not allowed' ;}
+mv "$temp_2" "$file_1" || { mv "$file_2" "$file_1" ; mv "$temp_2" "$file_2" ; non-user-error 4 'swap not allowed' ;}
diff --git a/filesets/home/bin/vpn- b/filesets/home/bin/vpn-
--- a/filesets/home/bin/vpn-
+++ b/filesets/home/bin/vpn-
@@ -34,7 +34,7 @@ source '/home/nestor/bin/std.lib'
 	while true; do
 		option="$1" && shift
 		case "$option" in
-			(--help) exit-out "$usage" ;;
+			(--help) help-and-exit ;;
 			(--) break ;;  # No more options.
 		esac
 	done
@@ -44,10 +44,10 @@ source '/home/nestor/bin/std.lib'
 { # -- Parameter Processing: Positionals -- #
 
 	network="$1" && shift
-	[ -n "$network" ] || error-out 1 'no NETWORK given'
+	[ -n "$network" ] || user-error 1 'no NETWORK given'
 
 
-	[ "$#" == 0 ] || error-out 1 'invalid option(s)'
+	[ "$#" == 0 ] || user-error 1 'invalid option(s)'
 
 }
 
@@ -57,13 +57,13 @@ source '/home/nestor/bin/std.lib'
 
 # Bail if there is no VPN host.
 #
-[ "$( gcp state vpn )" == 'RUNNING' ] || exit-out 0
+[ "$( gcp state vpn )" == 'RUNNING' ] || exit 0
 
 
 # Ensure the given NETWORK exists.
 #
 network_bins="${HOME}/vm-scripts/vpn/bin/${network}"
-[ -d "$network_bins" ] || error-out 2 "unknown NETWORK: '${network}'"
+[ -d "$network_bins" ] || user-error 2 "unknown NETWORK: '${network}'"
 
 
 ssh -n nestor@vpn -- "${network_bins}/disconnect"
